# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - display_name: Typeractive Corne Left
    artifact-name: typeractive_corne_left
    board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DZMK_CONFIG="${base_dir}/config/keyboards/corne-typeractive"
  - display_name: Typeractive Corne Right
    artifact-name: typeractive_corne_right
    board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    cmake-args: -DZMK_CONFIG="${base_dir}/config/keyboards/corne-typeractive"

    # PandaKB corne w/o dongle
  - display_name: PandaKB Corne Left
    artifact-name: pandakb_corne_left
    board: nice_nano_v2
    shield: pandakb_left nice_oled
    cmake-args: -DZMK_CONFIG="${base_dir}/config/keyboards/corne-pandakb" -DCONFIG_ZMK_SPLIT=y -DZMK_SPLIT_ROLE_CENTRAL=y
  - display_name: PandaKB Corne Right
    artifact-name: pandakb_corne_right
    board: nice_nano_v2
    shield: pandakb_right nice_oled
    cmake-args: -DZMK_CONFIG="${base_dir}/config/keyboards/corne-pandakb"

  - display_name: Prospector Dongle PandaKB
    artifact-name: prospector_dongle_pandakb
    board: seeeduino_xiao_ble
    shield: corne_dongle prospector_adapter
    cmake-args: -DZMK_CONFIG="${base_dir}/config/dongles/prospector"
  - display_name: Prospector Dongle Settings Reset
    artifact-name: prospector_dongle_reset
    board: seeeduino_xiao_ble
    shield: settings_reset
    cmake-args: -DZMK_CONFIG="${base_dir}/config/keyboards/corne-pandakb"

    # PandaKB corne with prospector dongle
  - display_name: PandaKB Corne Dongle Left
    artifact-name: pandakb_corne_dongle_left
    board: nice_nano_v2
    shield: pandakb_left nice_oled
    cmake-args: -DZMK_CONFIG="${base_dir}/config/keyboards/corne-pandakb" -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - display_name: PandaKB Corne Dongle Right
    artifact-name: pandakb_corne_dongle_right
    board: nice_nano_v2
    shield: pandakb_right nice_oled
    cmake-args: -DZMK_CONFIG="${base_dir}/config/keyboards/corne-pandakb" -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # firware to wipe flash memory. works for both typeractive and pandakb
  - display_name: Corne Settings Reset
    artifact-name: corne_reset
    board: nice_nano_v2
    shield: settings_reset
