on: [push, pull_request, workflow_dispatch]

jobs:
  build-corne-typeractive:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: config/keyboards/corne-typeractive/config
